spring:
  application:
    name: school-service

server:
  port: ${PORT:8332}

eureka:
  client.serviceUrl.defaultZone: ${EUREKA_SERVER_URI:http://localhost:8311/eureka}
  instance:
    hostname: ${APPLICATION_HOST_NAME:localhost}
    preferIpAddress: false

management:
  info.env.enabled: true
  endpoints:
    web:
      exposure:
        include: info

info:
  app:
    name: School Service
    Description: School Service
    version: 1.0.0