management:
  info.env.enabled: true
  endpoints:
    web:
      exposure:
        include: info

demo:
  appname:
    config: config-server
    eureka: eureka-server
    gateway: cloud-gateway
    school: school-service
    teacher: teacher-service
